#!/bin/sh
set -e

# If you want the logging enabled, create the log directory:
# > mkdir -p /var/log/psd
log_dir='/var/log/psd'

if [ -d "${log_dir}" ]; then
    exec svlogd -tt "${log_dir}"
else
    exec chpst -b psd-log-null cat >/dev/null
fi
