#!/bin/sh

[ -d '/var/cache/backlight/' ] || mkdir -p '/var/cache/backlight'
[ -w '/var/cache/backlight/' ] || chmod 755 '/var/cache/backlight/'

# Save current brightness of each card.
for card in `find /sys/class/backlight/ -type l`; do
    cp "$card/brightness" "/var/cache/backlight/$(basename $card)-brightness-old"
done
