#!/bin/sh

# If you want the logging enabled, create the log directory:
# > mkdir -p /var/log/colord
log_dir='/var/log/colord'

if [ -d "${log_dir}" ]; then
    exec svlogd -tt "${log_dir}"
else
    exec chpst -b colord-log-null cat >/dev/null
fi
